### ISSUE TITLE
thumbnail icon privacy is broken

### ISSUE THREAD

**Issue by propertunist** [Elgg/videolist#22]
1. create a video and save it as private
2. copy the url of the video's thumbnail
3. log out from elgg
4. open the url for the thumbnail in your browser
5. load the page with a cleared cache

result: the thumbnail will still load even though it is intended to be private.
desired: the thumbnail should not load when it's privacy setting is intended to keep it private.

comment: the version of the thumbnail code that is used in the file plugin for images does not suffer with this problem, though it does load the entire elgg engine, which is inefficient.

**Comment by mrclay** [comment]
Access to the entity *is* checked [here](https://github.com/Elgg/videolist/blob/master/thumbnail.php#L17). Do you have a proxy server (or mod_cache) which may be caching the thumbnail? We do always send the thumbnail with "public" cache headers, which isn't really appropriate unless the entity is public.

**Comment by propertunist** [comment]
ah that version of the file is different to mine. i think there are multiple forks of videolist. the version i have of thumbnail.php is the one that does not load the elgg engine for each thumbnail (gaining much performance as a result). without the engine being loaded, there is no check for access.
